# Generated by Django 5.1.2 on 2024-11-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_device_app_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='user_device_id',
            field=models.CharField(max_length=10, unique=True, blank=True, null=True),
        ),

    ]
