# Generated by Django 5.1.2 on 2024-11-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_device_user_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='user_device_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
