# Generated by Django 5.1.2 on 2024-11-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_device_user_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='user_device_id',
            field=models.CharField(default='D-DEFAULT', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
