# Generated by Django 5.1.2 on 2024-11-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_device_user_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.CharField(blank=True, max_length=255, null=True)),
                ('basic_specs', models.JSONField()),
            ],
        ),
    ]
