# Generated by Django 5.1.2 on 2024-11-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_phonespecs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='user_device_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
