# Generated by Django 5.1.2 on 2024-11-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_device_user_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonespecs',
            name='basic_specs',
        ),
        migrations.AddField(
            model_name='phonespecs',
            name='display_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='phonespecs',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phonespecs',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='phonespecs',
            name='release_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
